/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as UploadRouteImport } from './routes/upload'
import { Route as LogsRouteImport } from './routes/logs'
import { Route as CsvImportRouteImport } from './routes/csv-import'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppIdRouteImport } from './routes/app.$id'

const UploadRoute = UploadRouteImport.update({
  id: '/upload',
  path: '/upload',
  getParentRoute: () => rootRouteImport,
} as any)
const LogsRoute = LogsRouteImport.update({
  id: '/logs',
  path: '/logs',
  getParentRoute: () => rootRouteImport,
} as any)
const CsvImportRoute = CsvImportRouteImport.update({
  id: '/csv-import',
  path: '/csv-import',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIdRoute = AppIdRouteImport.update({
  id: '/app/$id',
  path: '/app/$id',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/csv-import': typeof CsvImportRoute
  '/logs': typeof LogsRoute
  '/upload': typeof UploadRoute
  '/app/$id': typeof AppIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/csv-import': typeof CsvImportRoute
  '/logs': typeof LogsRoute
  '/upload': typeof UploadRoute
  '/app/$id': typeof AppIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/csv-import': typeof CsvImportRoute
  '/logs': typeof LogsRoute
  '/upload': typeof UploadRoute
  '/app/$id': typeof AppIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/csv-import' | '/logs' | '/upload' | '/app/$id'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/csv-import' | '/logs' | '/upload' | '/app/$id'
  id: '__root__' | '/' | '/csv-import' | '/logs' | '/upload' | '/app/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CsvImportRoute: typeof CsvImportRoute
  LogsRoute: typeof LogsRoute
  UploadRoute: typeof UploadRoute
  AppIdRoute: typeof AppIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/upload': {
      id: '/upload'
      path: '/upload'
      fullPath: '/upload'
      preLoaderRoute: typeof UploadRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/logs': {
      id: '/logs'
      path: '/logs'
      fullPath: '/logs'
      preLoaderRoute: typeof LogsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/csv-import': {
      id: '/csv-import'
      path: '/csv-import'
      fullPath: '/csv-import'
      preLoaderRoute: typeof CsvImportRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/$id': {
      id: '/app/$id'
      path: '/app/$id'
      fullPath: '/app/$id'
      preLoaderRoute: typeof AppIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CsvImportRoute: CsvImportRoute,
  LogsRoute: LogsRoute,
  UploadRoute: UploadRoute,
  AppIdRoute: AppIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
